### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by hhayward-uptycs** [0xPrateek/Stardox#55] opened 2020-08-26 22:41 UTC
First of all, thank you...

I've tried this on a few repos and am getting this response:

`Traceback (most recent call last):
  File "stardox.py", line 384, in <module>
    stardox(repository_link,verbose,issave)
  File "stardox.py", line 327, in stardox
    structer.plotdata(len(data.username_list), pos, count)
  File "/Users/xxxxxxxxx/Desktop/Stardox/src/structer.py", line 20, in plotdata
    data.star_list[pos].strip(),
IndexError: list index out of range`

Any ideas?

**Comment by 0xPrateek** [comment] 2020-08-27 03:30
It's because of the issue #30 . 
It'll be fixed by today.
Thanks for using stardox

**Comment by 0xPrateek** [comment] 2020-08-27 16:31
Hey @hhayward-uptycs !
I've pushed 2 commits and the issue is fixed now.
Please verify it from your end.
Thanks.!

**Closed as completed** 2020-08-30 20:20 UTC

**Comment by hhayward-uptycs** [comment] 2020-08-31 22:20
Hey! I've tested this a few times across different sized repos (100, 2k, 30k) and I've been getting similar results:

`Traceback (most recent call last):
  File "stardox.py", line 383, in <module>
    stardox(repository_link,verbose,issave)
  File "stardox.py", line 326, in stardox
    structer.plotdata(len(data.username_list), pos, count)
  File "/Users/xxxxx/Desktop/Stardox/src/structer.py", line 37, in plotdata
    data.star_list[pos],
IndexError: list index out of range`

However, I have gotten a few results returned (7-9) whereas before I was getting none.

Thanks!

Harry
